name: "Setup BombSquad Environment"
description: "Common setup steps for BombSquad builds"

inputs:
  using-cmake:
    description: |
      "Set to true if building with cmake to enable caching"
      "Also sets up BA_APP_RUN_ENABLE_BUILDS env var"
    required: false
    type: boolean
    default: false

  static-build:
    description: "Set to true to prefer static libraries for cmake builds"
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
        cache-dependency-path: config/requirements.txt

    - name: Cache Bombsquad assets
      id: cache-assets
      uses: actions/cache@v4
      env:
        cache-name: cache-bombsquad-assets
      with:
        path: |
          build/assets
          .cache/efrocache/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.efrocachemap') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Setup project environment
      shell: bash
      run: make env
    - name: Update assets
      shell: bash
      run: |
        make assets-cmake
        make assets-windows

    - name: Install packages for static builds
      if: ${{ inputs.using-cmake == 'true' && inputs.static-build == 'true' }}
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          libopenal-dev \
          libsdl2-dev \
          libogg-dev \
          libvorbis-dev \
          libgl-dev \
          libpango1.0-dev \
          libcairo2-dev \
          libharfbuzz-dev \
          libglib2.0-dev \
          libstdc++-12-dev \
          libx11-dev \
          libxext-dev \
          libxrender-dev \
          libxcb1-dev \
          libfontconfig-dev \
          libfreetype6-dev \
          libpng-dev \
          zlib1g-dev \
          libffi-dev \
          libpcre2-dev \
          libexpat1-dev \
          libmount-dev \
          libdatrie-dev \
          libbz2-dev \
          libbrotli-dev

    # Following steps only run for inputs.using-cmake == 'true'
    - name: Install build packgages
      if: ${{ inputs.using-cmake == 'true' }}
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          libglut-dev \
          libopenal-dev \
          libsdl2-dev \
          libvorbis-dev

    - name: Setup env variables
      if: ${{ inputs.using-cmake == 'true' }}
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "BA_APP_RUN_ENABLE_BUILDS=1" >> $GITHUB_ENV
        echo CMAKE_EXTRA_ARGS="-DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV

    - name: Setup sccache
      if: ${{ inputs.using-cmake == 'true' }}
      uses: mozilla-actions/sccache-action@v0.0.9
      with:
        disable_annotations: true
