name: 'Setup BombSquad Environment'
description: 'Common setup steps for BombSquad builds'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Cache Python venv
      id: cache-venv
      uses: actions/cache@v4
      env:
        cache-name: cache-python-venv
      with:
        path: |
          .venv
          .cache/checkenv
        key: ${{ runner.os }}-${{runner.arch}}-${{ env.cache-name }}-${{ hashFiles('config/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{runner.arch}}-${{ env.cache-name }}-
    - name: Cache Bombsquad assets
      id: cache-assets
      uses: actions/cache@v4
      env:
        cache-name: cache-bombsquad-assets
      with:
        path: |
          build/assets
          .cache/efrocache/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.efrocachemap') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
    - name: Restore CMake build cache
      id: cache-cmake-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          build/cmake
        key: ${{ runner.os }}-${{ runner.arch }}-cmake-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-cmake-build-
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Setup project environment
      run: make env
      shell: bash